export enum QuestionType {
  FreeText = 'Free-Text',
  MCQ = 'MCQ',
  Rating = 'Rating',
  Likert = 'Likert',
  YesNo = 'Yes-No',
  Ranking = 'Ranking',
  Matching = 'Matching',
  FillInTheBlank = 'Fill-in-the-Blank',
  PictureChoice = 'Picture-Choice',
  Slider = 'Slider',
  Dropdown = 'Dropdown',
  SemanticDifferential = 'Semantic-Differential',
  Matrix = 'Matrix',
  Demographic = 'Demographic',
  Hotspot = 'Hotspot',
  DragAndDrop = 'Drag-and-Drop',
}
